Agents:
  WebAgent:
    class_name: 'fast.common.agents.WebBrowserAgent'
    headless: no
    headlessBrowser: chrome
    driverClassName: 'org.openqa.selenium.chrome.ChromeDriver'
    webDriverPath: drivers/webdriver/chromedriver.exe
#'org.openqa.selenium.ie.InternetExplorerDriver'
    webRepo: repos/locator
    chromeArgument: '--no-sandbox;--disable-dev-shm-usage'
    chromePrefs:
      download.default_directory:
    #proxy:host:port
    username: xs04344
    password: c9 b2 fb 64 0c 1f 23 d7 8b 3a 23 47 54 18 8a 31

#    DesktopAgent:
#      class: 'fast.common.agents.UiaAgent'